import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { advertisementLinks } from "~/temporarydb/advertisements";
import AdsMenu from "~/components/AdsMenu";
import Footer from "~/components/Footer";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const adLinks = advertisementLinks;
  return (
    <html lang="en">
      <body className={`bg-advertisement-bg font-sans ${inter.variable}`}>
        <AdsMenu links={adLinks} />
        {children}
        <Footer />
      </body>
    </html>
  );
}
